# Generated by Django 5.0 on 2025-02-06 03:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("industry", models.CharField(blank=True, max_length=100)),
                ("website", models.URLField(blank=True)),
                ("logo_url", models.URLField(blank=True)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ApplicationRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "outcome",
                    models.TextField(
                        choices=[
                            ("TO DO", "TO DO"),
                            ("IN PROGRESS", "IN PROGRESS"),
                            ("REFER", "REFER"),
                            ("REJECT(Resume)", "REJECT(Resume)"),
                            ("REJECT(VO)", "REJECT(VO)"),
                            ("REJECT(OA)", "REJECT(OA)"),
                            ("VO", "VO"),
                            ("OA", "OA"),
                            ("OFFER", "OFFER"),
                        ]
                    ),
                ),
                ("job_title", models.TextField(blank=True)),
                ("company_name", models.TextField()),
                ("application_link", models.TextField(blank=True)),
                ("OA_date", models.DateTimeField(blank=True, null=True)),
                ("VO_date", models.DateTimeField(blank=True, null=True)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        default="cyuan8",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        to_field="username",
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="EmailThread",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("thread_id", models.CharField(max_length=100)),
                ("subject", models.CharField(max_length=500)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_threads",
                        to="tracks.applicationrecord",
                    ),
                ),
            ],
            options={
                "unique_together": {("application", "thread_id")},
            },
        ),
        migrations.CreateModel(
            name="EmailMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message_id", models.CharField(max_length=100, unique=True)),
                ("sender", models.EmailField(max_length=254)),
                ("recipient", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=500)),
                ("body", models.TextField()),
                ("sent_at", models.DateTimeField()),
                ("raw_payload", models.JSONField(blank=True, null=True)),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="tracks.emailthread",
                    ),
                ),
            ],
            options={
                "ordering": ["sent_at"],
            },
        ),
    ]
