# Generated by Django 5.0 on 2025-02-06 03:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobPosting",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("company_name", models.CharField(max_length=200)),
                (
                    "locations",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200), size=None
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("date_posted", models.BigIntegerField()),
                (
                    "terms",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100), size=None
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("url", models.URLField(max_length=500)),
                ("is_visible", models.BooleanField(default=True)),
                ("source", models.CharField(max_length=100)),
                ("company_url", models.URLField(blank=True, max_length=500)),
                ("date_updated", models.BigIntegerField()),
                ("sponsorship", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["-date_posted"],
                "indexes": [
                    models.Index(
                        fields=["company_name"], name="jobgpt_jobp_company_db9e98_idx"
                    ),
                    models.Index(
                        fields=["date_posted"], name="jobgpt_jobp_date_po_d803de_idx"
                    ),
                    models.Index(
                        fields=["active"], name="jobgpt_jobp_active_6d9139_idx"
                    ),
                    models.Index(
                        fields=["is_visible"], name="jobgpt_jobp_is_visi_3712f3_idx"
                    ),
                ],
            },
        ),
    ]
