version: '3.8'

# This docker-compose.yml is kept for local Supabase development
# The main application is now frontend-only and deployed to Vercel

services:
  # Frontend development server
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: npm run dev

volumes:
  node_modules:
