/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * User login
         * @description Authenticate user with username and password
         */
        post: operations["loginUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * User registration
         * @description Create a new user account
         */
        post: operations["registerUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh access token
         * @description Get a new access token using refresh token
         */
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/user/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current user
         * @description Retrieve information about the currently authenticated user
         */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all applications
         * @description Retrieve all job applications for the current user
         */
        get: operations["listApplications"];
        put?: never;
        /**
         * Create a new application
         * @description Record a new job application
         */
        post: operations["createApplication"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get application details
         * @description Retrieve details of a specific application
         */
        get: operations["getApplication"];
        /**
         * Update application
         * @description Update a job application record
         */
        put: operations["updateApplication"];
        post?: never;
        /**
         * Delete application
         * @description Delete a job application record
         */
        delete: operations["deleteApplication"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get user profile
         * @description Retrieve the current user's profile information
         */
        get: operations["getUserProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update user profile
         * @description Update user profile including resume upload/deletion
         */
        patch: operations["updateUserProfile"];
        trace?: never;
    };
    "/api/job-applications/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List job applications (MongoDB)
         * @description Retrieve advanced job application records with detailed tracking
         */
        get: operations["listJobApplications"];
        put?: never;
        /**
         * Create job application
         * @description Record a new advanced job application with full tracking
         */
        post: operations["createJobApplication"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        User: {
            /** @example 1 */
            id: number;
            /** @example john_doe */
            username: string;
            /**
             * Format: email
             * @example john@example.com
             */
            email: string;
        };
        Application: {
            /** @example 1 */
            id: number;
            company: {
                /** @example 1 */
                id?: number;
                /** @example Google */
                name?: string;
                description?: string | null;
                industry?: string | null;
            };
            /** @example Software Engineer */
            job_title: string;
            /**
             * @example APPLIED
             * @enum {string}
             */
            status: "APPLIED" | "OA" | "VO" | "OFFER" | "REJECTED";
            /**
             * @description Application source (LinkedIn, email, referral, etc.)
             * @example LinkedIn
             */
            source?: string;
            notes?: string | null;
            /** @description Associated email ID for tracking */
            email_id?: string | null;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        ApplicationInput: {
            company: {
                /** @example 1 */
                id: number;
                /** @example Google */
                name?: string;
            };
            /** @example Software Engineer */
            job_title: string;
            /**
             * @example APPLIED
             * @enum {string}
             */
            status: "APPLIED" | "OA" | "VO" | "OFFER" | "REJECTED";
            /** @example LinkedIn */
            source?: string;
            notes?: string | null;
            email_id?: string | null;
        };
        UserProfile: {
            id: number;
            user: components["schemas"]["User"];
            /** @description Resume file path */
            resume?: string | null;
            resume_name?: string | null;
            /** Format: date-time */
            resume_updated_at?: string | null;
            /** Format: uri */
            resume_url?: string | null;
        };
        JobApplication: {
            /**
             * @description MongoDB ObjectId
             * @example 69f90cc9052f5e8cf4ac98f8
             */
            _id?: string;
            company?: {
                /** @example Attention */
                name?: string;
                /** @example AI / Sales Intelligence */
                industry?: string;
                /** @example Series A */
                stage?: string;
                /** @example $17M */
                funding?: string;
                location?: {
                    city?: string;
                    state?: string;
                    neighborhood?: string | null;
                    /** @enum {string} */
                    remote_policy?: "remote" | "hybrid" | "on-site";
                    office_days_required?: number | null;
                };
            };
            role?: {
                /** @example Full Stack Engineer */
                title?: string;
                /** @enum {string} */
                level?: "entry" | "mid" | "senior";
                department?: string;
                /** @enum {string} */
                type?: "full-time" | "part-time" | "contract" | "internship";
                salary_range?: {
                    min?: number | null;
                    max?: number | null;
                    currency?: string;
                };
            };
            /** @enum {string} */
            status?: "resume_submitted" | "screening_scheduled" | "screening_done" | "interview_scheduled" | "interview_done" | "offer_received" | "offer_accepted" | "offer_declined" | "rejected" | "ghosted";
            /** @example recruiter_outreach */
            source?: string;
            recruiter?: {
                name?: string;
                /** Format: email */
                email?: string;
                agency?: string | null;
            };
            timeline?: {
                /** Format: date-time */
                date?: string;
                event?: string;
                /** @enum {string} */
                direction?: "inbound" | "outbound";
                medium?: string;
                notes?: string;
            }[];
            meta?: {
                /** Format: date-time */
                created_at?: string;
                /** Format: date-time */
                updated_at?: string;
                next_action?: string;
                /** Format: date-time */
                next_action_date?: string;
                /** @enum {string} */
                priority?: "low" | "medium" | "high";
                tags?: string[];
            };
        };
        JobApplicationInput: {
            company: {
                name: string;
                industry?: string;
                stage?: string;
                funding?: string;
                location?: Record<string, never>;
            };
            role: {
                title: string;
                level?: string;
                department?: string;
                type?: string;
            };
            /** @example resume_submitted */
            status: string;
            source?: string;
            recruiter?: {
                name?: string;
                email?: string;
            };
            meta?: {
                priority?: string;
                tags?: string[];
            };
        };
        ErrorResponse: {
            /** @description Error message */
            detail: string;
            /** @description Error code */
            code?: string;
        };
    };
    responses: {
        /** @description Bad request - invalid input */
        BadRequestError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Unauthorized - missing or invalid authentication */
        UnauthorizedError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource not found */
        NotFoundError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    loginUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example john_doe */
                    username: string;
                    /**
                     * Format: password
                     * @example securepassword123
                     */
                    password: string;
                };
            };
        };
        responses: {
            /** @description Login successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description JWT access token
                         * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
                         */
                        access?: string;
                        /**
                         * @description JWT refresh token
                         * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
                         */
                        refresh?: string;
                        user?: components["schemas"]["User"];
                    };
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
        };
    };
    registerUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example john_doe */
                    username: string;
                    /**
                     * Format: email
                     * @example john@example.com
                     */
                    email: string;
                    /**
                     * Format: password
                     * @example securepassword123
                     */
                    password: string;
                    /**
                     * Format: password
                     * @description Password confirmation
                     * @example securepassword123
                     */
                    password2: string;
                };
            };
        };
        responses: {
            /** @description User registered successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["BadRequestError"];
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description Refresh token
                     * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
                     */
                    refresh: string;
                };
            };
        };
        responses: {
            /** @description Token refreshed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description New JWT access token */
                        access?: string;
                    };
                };
            };
            401: components["responses"]["UnauthorizedError"];
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user information */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
        };
    };
    listApplications: {
        parameters: {
            query?: {
                /** @description Filter by application status */
                status?: "APPLIED" | "OA" | "VO" | "OFFER" | "REJECTED";
                /** @description Filter by company ID */
                company_id?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of applications */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Application"][];
                };
            };
            401: components["responses"]["UnauthorizedError"];
        };
    };
    createApplication: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationInput"];
            };
        };
        responses: {
            /** @description Application created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Application"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
        };
    };
    getApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Application ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Application details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Application"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            404: components["responses"]["NotFoundError"];
        };
    };
    updateApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Application ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationInput"];
            };
        };
        responses: {
            /** @description Application updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Application"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            404: components["responses"]["NotFoundError"];
        };
    };
    deleteApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Application ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Application deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["UnauthorizedError"];
            404: components["responses"]["NotFoundError"];
        };
    };
    getUserProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
        };
    };
    updateUserProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description Resume file upload
                     */
                    resume?: string;
                    /** @description Resume name (set to null to delete) */
                    resume_name?: string | null;
                };
                "application/json": {
                    /** @description Resume file path or null to delete */
                    resume?: string | null;
                    resume_name?: string | null;
                };
            };
        };
        responses: {
            /** @description Profile updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
        };
    };
    listJobApplications: {
        parameters: {
            query?: {
                /** @description Filter by application status */
                status?: "resume_submitted" | "screening_scheduled" | "screening_done" | "interview_scheduled" | "interview_done" | "offer_received" | "offer_accepted" | "offer_declined" | "rejected" | "ghosted";
                /** @description Filter by company name */
                company_name?: string;
                /** @description Filter by priority level */
                priority?: "low" | "medium" | "high";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of job applications */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobApplication"][];
                };
            };
            401: components["responses"]["UnauthorizedError"];
        };
    };
    createJobApplication: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobApplicationInput"];
            };
        };
        responses: {
            /** @description Job application created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobApplication"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
        };
    };
}
