# Generated by Django 5.0 on 2025-01-26 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="company",
        ),
        migrations.RemoveField(
            model_name="job",
            name="applicants",
        ),
        migrations.DeleteModel(
            name="Company",
        ),
        migrations.DeleteModel(
            name="Job",
        ),
    ]
